### ISSUE TITLE
booktreeの取得が若干遅い

### ISSUE THREAD

**Issue by karintou8710** [takapiro99/book-tree#46]

**Comment by takapiro99** [comment]
functions で一つずつ functions.https.onRequest を生やしてるが遅さに関係してるかな（あくまで予測です）

example には 一つの onRequest を express のインスタンスみたいにしてて、その中でルーティングとかしていた

**Comment by takapiro99** [comment]
メモリ 1GB、region を asia-northeast1 にすることでとりあえず速くなった
